let arr=["FOOD PREPARATION / DIPLOMA IN CULINARY ARTS","BARISTA (COFFEE MAKING)","F & B SERVICE (WAITER/WAITRESS)","BARTENDER TRAINING","FRONT OFFICE TRAINING","HOUSEKEEPING TRAINING","BAKERY"]


export default arr.map((each,k)=> ({label:each,value:k+1}))


